# Generated by Django 5.1.11 on 2025-08-28 16:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('in_test', 'In Test'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='waiting', max_length=15)),
                ('position', models.IntegerField()),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_time', models.DateTimeField(blank=True, null=True)),
                ('no_show_check_time', models.DateTimeField(blank=True, null=True)),
                ('actual_wait_time', models.IntegerField(blank=True, null=True)),
                ('consultation_start', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('max_capacity', models.IntegerField(default=50)),
                ('avg_processing_time', models.IntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='hospital.department')),
            ],
            options={
                'ordering': ['department__name', 'name'],
                'permissions': [('can_manage_queue', 'Can manage queue operations')],
            },
        ),
        migrations.CreateModel(
            name='QueueAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_patients', models.IntegerField(default=0)),
                ('avg_wait_time', models.FloatField(default=0.0)),
                ('avg_processing_time', models.FloatField(default=0.0)),
                ('no_show_count', models.IntegerField(default=0)),
                ('peak_hour_start', models.TimeField(blank=True, null=True)),
                ('peak_hour_end', models.TimeField(blank=True, null=True)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queues.queue')),
            ],
        ),
    ]
