# Generated by Django 5.1.11 on 2025-08-21 14:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_position', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('max_capacity', models.IntegerField(default=50)),
                ('estimated_wait_time', models.IntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
            ],
            options={
                'ordering': ['department__name'],
                'permissions': [('can_manage_queue', 'Can manage queue operations')],
            },
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(choices=[(0, 'Emergency'), (1, 'Urgent'), (2, 'Standard'), (3, 'Low')], default=2)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('position', models.IntegerField()),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='queues.patientqueue')),
            ],
            options={
                'ordering': ['priority', 'joined_at'],
                'indexes': [models.Index(fields=['queue', 'status'], name='queues_queu_queue_i_90b16e_idx'), models.Index(fields=['priority', 'joined_at'], name='queues_queu_priorit_454408_idx')],
                'unique_together': {('queue', 'patient', 'status')},
            },
        ),
    ]
