# Generated by Django 5.1.11 on 2025-08-28 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queues', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queues.queue'),
        ),
        migrations.AlterUniqueTogether(
            name='queueanalytics',
            unique_together={('queue', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='queueentry',
            unique_together={('patient', 'queue')},
        ),
    ]
