"""
Django settings for smartqueue project.

Generated by 'django-admin startproject' using Django 5.1.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)#ed^pdgjv#s61307#c!+2d9p!cfp-6ryyiph0xg(r-i@+es4v'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'users',
    'hospital',
    'debug_toolbar',
    'rest_framework.authtoken',  # Add token authentication
    'django_filters',
    'departments',
    'queues',
]

MIDDLEWARE = [
    'csp.middleware.CSPMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'smartqueue.security_middleware.SecurityMiddleware',  # Custom security middleware
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'smartqueue.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smartqueue.wsgi.application'

INTERNAL_IPS = [
    # ... '127.0.0.1',
    '127.0.0.1',
    'localhost',
]
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/
# Language and timezone settings
LANGUAGE_CODE = 'en-us'  # Default language for the project
TIME_ZONE = 'UTC'        # Default timezone

USE_I18N = True          # Enable Django's internationalization system
USE_TZ = True            # Enable timezone-aware datetimes

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL = 'static/'   # URL to use when referring to static files

# Media files (User uploaded files)
MEDIA_URL = '/media/'    # URL to use when referring to media files
MEDIA_ROOT = BASE_DIR / 'media'  # Directory to store uploaded media files

# settings.py
# STATIC_URL = '/static/'
# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# STATIC_URL = '/static/'
# STATICFILES_DIRS = [BASE_DIR / "blog" / "static"]
# STATIC_ROOT = BASE_DIR / "staticfiles"   # useful for collectstatic in production



# Custom user model
AUTH_USER_MODEL = 'users.CustomUser'  # Reference to custom user model

# Argon2 password hasher
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',      # Strong password hashing algorithm
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',      # PBKDF2 hasher
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',  # PBKDF2 SHA1 hasher
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',# BCrypt SHA256 hasher
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'  # Default auto field for models

# Django REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # Use JWT for authentication
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',  # Throttle for authenticated users
        'rest_framework.throttling.AnonRateThrottle',  # Throttle for anonymous users
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '100/hour',  # 100 requests/hour for authenticated users
        'anon': '5/hour',    # 5 requests/hour for non-logged-in users
        'queue_join': '3/hour',  # 3 requests/hour to join a queue
    },
     'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# Simple JWT configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),  # Access token valid for 30 minutes
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),     # Refresh token valid for 1 day
}
# Redirect URLs after login/logout
LOGIN_REDIRECT_URL = "/"  # Redirect to home after successful login
LOGOUT_REDIRECT_URL = "/"  # Redirect to home after logout

# =============================================================================
# SECURITY SETTINGS
# =============================================================================

# SECURITY WARNING: In production, set DEBUG = False and configure ALLOWED_HOSTS
DEBUG = True  # Set to False in production for security
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']  # Add your domain in production

# Security Middleware Configuration
SECURE_BROWSER_XSS_FILTER = True  # Enable browser XSS protection
SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent the browser from guessing content types
X_FRAME_OPTIONS = 'DENY'  # Prevent site from being rendered in a frame (clickjacking protection)

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # Use this header to determine SSL status when behind a proxy

# CSRF cookie settings
CSRF_COOKIE_SECURE = False  # Set to True in production to send CSRF cookie only over HTTPS
CSRF_COOKIE_HTTPONLY = True  # Prevent JavaScript access to CSRF cookie
CSRF_COOKIE_SAMESITE = 'Strict'  # Restrict CSRF cookie to same-site requests

# Session cookie settings
SESSION_COOKIE_SECURE = False  # Set to True in production to send session cookie only over HTTPS
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
SESSION_COOKIE_SAMESITE = 'Strict'  # Restrict session cookie to same-site requests
SESSION_COOKIE_AGE = 3600  # Session cookie lifetime in seconds (1 hour)

SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'  # Control information sent in Referer header

# Additional Security Headers
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
# Content Security Policy (CSP) settings are not natively supported by Django.
# To enforce CSP, use a third-party package like 'django-csp' and configure it accordingly.


# Logging Configuration for Security Monitoring
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'security.log',  # Log security warnings/errors to file
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django.security': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',  # Log security warnings
            'propagate': True,
        },
        'django.request': {
            'handlers': ['file', 'console'],
            'level': 'ERROR',  # Log request errors
            'propagate': True,
        },
    },
}
