# Generated by Django 5.1.11 on 2025-08-28 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department_type', models.CharField(choices=[('OPD', 'Outpatient Department'), ('LAB', 'Laboratory'), ('PHARMACY', 'Pharmacy'), ('ER', 'Emergency Room')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('can_manage_department', 'Can manage department settings')],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('staff', 'Staff')], max_length=10)),
                ('specialty', models.CharField(blank=True, choices=[('general', 'General Medicine'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('emergency', 'Emergency Medicine')], max_length=20)),
                ('license_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('is_on_break', models.BooleanField(default=False)),
                ('avg_consultation_time', models.IntegerField(default=15)),
                ('is_primary', models.BooleanField(default=False)),
                ('can_manage_queue', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.department')),
            ],
            options={
                'verbose_name_plural': 'Staff',
            },
        ),
    ]
